# Generated by Django 5.2.17 on 2026-10-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('seller', 'Vendedor'), ('cashier', 'Caixa'), ('finance', 'Financeiro')], max_length=20, verbose_name='Perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.store', verbose_name='Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo com loja',
                'verbose_name_plural': 'Vínculos com lojas',
                'ordering': ['store__code', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='unique_user_store_membership')],
            },
        ),
    ]
