# Generated by Django 5.2.17 on 2026-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_storemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Automático')], default='system', max_length=10, verbose_name='Tema'),
        ),
    ]
