# Generated by Django 5.2.17 on 2026-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='NÃºmero'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_type',
            field=models.CharField(choices=[('individual', 'Pessoa FÃ\xadsica'), ('company', 'Pessoa JurÃ\xaddica')], default='individual', max_length=10, verbose_name='Tipo de pessoa'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='InscriÃ§Ã£o estadual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trade_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome fantasia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome completo / RazÃ£o social'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='CÃ³digo'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), models.Q(('cnpj', ''), _negated=True)), fields=('store', 'cnpj'), name='unique_customer_cnpj_per_store'),
        ),
    ]
