# Generated by Django 5.2.17 on 2026-10-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_customer_address_complement_customer_address_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_type',
            field=models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='individual', max_length=10, verbose_name='Tipo de pessoa'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(db_index=True, max_length=30, verbose_name='Código interno')),
                ('barcode', models.CharField(blank=True, max_length=30, verbose_name='Código de barras')),
                ('name', models.CharField(max_length=180, verbose_name='Descrição')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de custo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de venda')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque atual')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='organizations.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'internal_code'), name='unique_product_code_per_store'), models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('store', 'barcode'), name='unique_product_barcode_per_store'), models.CheckConstraint(condition=models.Q(('cost_price__gte', 0), ('sale_price__gte', 0), ('stock_quantity__gte', 0), ('minimum_stock__gte', 0)), name='product_numeric_values_non_negative')],
            },
        ),
    ]
