# Generated by Django 5.2.17 on 2026-10-08 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_customer_address_number_alter_customer_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste por contagem')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade informada')),
                ('balance_before', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo anterior')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo posterior')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.product', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_after__gte', 0), ('balance_before__gte', 0)), name='stock_movement_non_negative_balances'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['entry', 'exit']), ('quantity__gt', 0)), models.Q(('movement_type', 'adjustment'), ('quantity__gte', 0)), _connector='OR'), name='stock_movement_valid_type_quantity')],
            },
        ),
    ]
