# Generated by Django 5.2.17 on 2026-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_stockmovement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_numeric_values_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='stock_movement_non_negative_balances',
        ),
        migrations.AddField(
            model_name='store',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, verbose_name='Permitir estoque negativo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome completo / Razão social'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0), ('sale_price__gte', 0), ('minimum_stock__gte', 0)), name='product_numeric_values_non_negative'),
        ),
    ]
