# Generated by Django 5.2.17 on 2026-10-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_stockmovement'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('completed', 'Finalização'), ('cancelled', 'Cancelamento')], max_length=12, verbose_name='Operação')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_events', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Evento da venda',
                'verbose_name_plural': 'Eventos das vendas',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.saleevent', verbose_name='Evento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.saleitem', verbose_name='Item')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_link', to='organizations.stockmovement', verbose_name='Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação da venda',
                'verbose_name_plural': 'Movimentações das vendas',
            },
        ),
        migrations.AddConstraint(
            model_name='saleevent',
            constraint=models.UniqueConstraint(fields=('sale', 'event_type'), name='unique_event_type_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='saleevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type', 'completed'), models.Q(('event_type', 'cancelled'), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='sale_event_type_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='salestockmovement',
            constraint=models.UniqueConstraint(fields=('event', 'item'), name='unique_stock_movement_per_event_item'),
        ),
    ]
