# Generated by Django 5.2.17 on 2026-10-09 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_stockmovement'),
        ('sales', '0002_saleevent_salestockmovement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operação de venda',
                'verbose_name_plural': 'Operações de venda',
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Conta de recebimento',
                'verbose_name_plural': 'Contas de recebimento',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor lançado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('reason', models.CharField(max_length=255, verbose_name='Descrição')),
                ('request_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Identificador da operação')),
            ],
            options={
                'verbose_name': 'Lançamento de recebimento',
                'verbose_name_plural': 'Lançamentos de recebimento',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('transfer', 'Transferência'), ('debit', 'Cartão de débito'), ('credit', 'Cartão de crédito'), ('store_credit', 'Crediário'), ('boleto', 'Boleto')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Parcela')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('debtor', models.CharField(choices=[('customer', 'Cliente'), ('operator', 'Operadora de cartão')], max_length=10, verbose_name='Responsável')),
                ('customer_name', models.CharField(blank=True, max_length=180, verbose_name='Cliente registrado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Parcela a receber',
                'verbose_name_plural': 'Parcelas a receber',
                'ordering': ['due_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(editable=False, max_length=100, verbose_name='Forma registrada')),
                ('kind', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('transfer', 'Transferência'), ('debit', 'Cartão de débito'), ('credit', 'Cartão de crédito'), ('store_credit', 'Crediário'), ('boleto', 'Boleto')], editable=False, max_length=20, verbose_name='Tipo registrado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('installment_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Parcelas')),
                ('first_due_date', models.DateField(verbose_name='Primeiro vencimento')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Recebimento confirmado')),
            ],
            options={
                'verbose_name': 'Pagamento da venda',
                'verbose_name_plural': 'Pagamentos da venda',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto da venda (R$)'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sale_discount_nonnegative'),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.store', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='sales.financialaccount', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='sales.financialentry', verbose_name='Estorno de'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.store', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.paymentmethod', verbose_name='Forma de recebimento'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='sales.receivable', verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.financialaccount', verbose_name='Conta de recebimento'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.paymentmethod', verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='sales.salepayment', verbose_name='Pagamento'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_financial_account_store_code'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_payment_method_store_code'),
        ),
        migrations.AddConstraint(
            model_name='financialentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('reversal_of__isnull', True)), models.Q(('amount__lt', 0), ('reversal_of__isnull', False)), _connector='OR'), name='financial_entry_sign_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('installment_count__gte', 1), ('installment_count__lte', 12)), name='sale_payment_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.UniqueConstraint(fields=('payment', 'number'), name='unique_receivable_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('number__gte', 1)), name='receivable_values_valid'),
        ),
    ]
