# Generated by Django 5.2.17 on 2026-10-09 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_product_product_numeric_values_non_negative_and_more'),
        ('sales', '0003_checkoutrequest_financialaccount_financialentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request', 'Solicitação'), ('approve', 'Autorização'), ('reject', 'Recusa')], max_length=10, verbose_name='Operação')),
                ('snapshot_hash', models.CharField(editable=False, max_length=64, verbose_name='Identificador dos valores')),
                ('role', models.CharField(max_length=30, verbose_name='Perfil registrado')),
                ('limit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Limite registrado (%)')),
                ('reference_subtotal', models.DecimalField(decimal_places=2, max_digits=28, verbose_name='Subtotal de referência')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=28, verbose_name='Desconto considerado')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Registro de autorização de desconto',
                'verbose_name_plural': 'Registros de autorização de desconto',
                'ordering': ['created_at', 'pk'],
                'permissions': [('approve_discount', 'Pode autorizar descontos acima do limite')],
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('seller', 'Vendedor'), ('cashier', 'Caixa'), ('finance', 'Financeiro')], max_length=30, verbose_name='Perfil')),
                ('limit_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Desconto máximo (%)')),
            ],
            options={
                'verbose_name': 'Limite de desconto por perfil',
                'verbose_name_plural': 'Limites de desconto por perfil',
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de referência'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('reference_price__isnull', True), ('reference_price__gte', 0), _connector='OR'), name='sale_item_reference_price_valid'),
        ),
        migrations.AddField(
            model_name='discountauthorization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='discountauthorization',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='sales.discountauthorization', verbose_name='Solicitação original'),
        ),
        migrations.AddField(
            model_name='discountauthorization',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_authorizations', to='sales.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_policies', to='organizations.store', verbose_name='Unidade'),
        ),
        migrations.AddConstraint(
            model_name='discountauthorization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'request'), ('request__isnull', True)), models.Q(('action__in', ['approve', 'reject']), ('request__isnull', False)), _connector='OR'), name='discount_action_request_consistent'),
        ),
        migrations.AddConstraint(
            model_name='discountauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0), ('limit_percentage__gte', 0), ('limit_percentage__lte', 100), ('reference_subtotal__gte', 0)), name='discount_authorization_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='discountpolicy',
            constraint=models.UniqueConstraint(fields=('store', 'role'), name='unique_discount_policy_store_role'),
        ),
        migrations.AddConstraint(
            model_name='discountpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('limit_percentage__gte', 0), ('limit_percentage__lte', 100)), name='discount_policy_percentage_valid'),
        ),
    ]
