# Generated by Django 5.2.17 on 2026-10-09 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_product_product_numeric_values_non_negative_and_more'),
        ('sales', '0004_discountauthorization_discountpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='max_installments',
            field=models.PositiveSmallIntegerField(default=12, help_text='De 1 a 12 para crédito, boleto e crediário. Dinheiro, Pix, transferência e débito aceitam uma parcela.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Máximo de parcelas'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='interval_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Intervalo entre parcelas'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='interval_unit',
            field=models.CharField(choices=[('months', 'Meses'), ('days', 'Dias')], default='months', max_length=6, verbose_name='Unidade do intervalo'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.CheckConstraint(condition=models.Q(('max_installments__gte', 1), ('max_installments__lte', 12)), name='payment_method_installment_limit_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interval_count__gte', 1), ('interval_count__lte', 365), ('interval_unit', 'days')), models.Q(('interval_count__gte', 1), ('interval_count__lte', 12), ('interval_unit', 'months')), _connector='OR'), name='sale_payment_interval_valid'),
        ),
    ]
